development:
  adapter: sqlite3
  database: db/baseball_stats_dev.sqlite3
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: baseball_stats
  encoding: utf8
  host: localhost
  port: 5432
  username: postgres
  password:

test: &test
  adapter: sqlite3
  database: db/baseball_stats_test.sqlite3
  pool: 5
  timeout: 5000
